services:
  postgres:
    image: postgres
    container_name: pfm_dev_postgres
    environment:
      POSTGRES_PASSWORD: 'dev'
      POSTGRES_DB: 'pfm'
    ports:
      - 9004:5432
    volumes:
      - postgres_data:/var/lib/postgres

  redis:
    image: redis
    container_name: pfm_dev_redis
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=${REDIS_HOST_DOCKER}
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes"]

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=redis:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis

  pfm_dev_api:
    image: pfm-api:${APP_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: api
    container_name: pfm_dev_api
    depends_on:
      - postgres
      - redis
    ports:
      - '9778:3000'
    env_file:
      - ./.env
    environment:
      - APP_NAME=api
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - REDIS_HOST=${REDIS_HOST_DOCKER}
    deploy:
      resources:
        limits:
          cpus: '0.95'
          memory: 512M
        reservations:
          memory: 256M

  pfm_dev_workers:
    image: pfm-workers:${APP_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: workers
    container_name: pfm_dev_workers
    depends_on:
      - pfm_dev_api
      - redis
    env_file:
      - ./.env
    environment:
      - APP_NAME=workers
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - REDIS_HOST=${REDIS_HOST_DOCKER}
    deploy:
      resources:
        limits:
          cpus: '0.95'
          memory: 512M
        reservations:
          memory: 256M

volumes:
  redis_data:
  postgres_data:
